# PyTorch tutorial

## Попов Артём

In [1]:
import torch
import numpy as np

## Тензоры

В интерфейсе базовых операций тензор мало отличается от np.array:

In [2]:
x = torch.Tensor(5, 3)

In [5]:
x = torch.zeros(5, 3)

In [6]:
x


 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
[torch.FloatTensor of size 5x3]

In [7]:
x = torch.ones(5, 3)

In [8]:
x * 5


 5  5  5
 5  5  5
 5  5  5
 5  5  5
 5  5  5
[torch.FloatTensor of size 5x3]

In [52]:
x = torch.randn(5, 3)
x


-0.1989  0.3665 -0.2036
 2.3245 -0.4085 -1.2753
-1.6898 -1.1646  2.0157
 0.0355 -0.9913  0.6183
-1.2959 -0.8383 -1.0868
[torch.FloatTensor of size 5x3]

In [53]:
print(x.transpose(0, 1))
print(x.size())


-0.1989  2.3245 -1.6898  0.0355 -1.2959
 0.3665 -0.4085 -1.1646 -0.9913 -0.8383
-0.2036 -1.2753  2.0157  0.6183 -1.0868
[torch.FloatTensor of size 3x5]

torch.Size([5, 3])


In [54]:
print(torch.transpose(x, 0, 1))
print(x.size())


-0.1989  2.3245 -1.6898  0.0355 -1.2959
 0.3665 -0.4085 -1.1646 -0.9913 -0.8383
-0.2036 -1.2753  2.0157  0.6183 -1.0868
[torch.FloatTensor of size 3x5]

torch.Size([5, 3])


Сложение

In [55]:
y = torch.rand(5, 3)
print(x + y)


 0.1945  0.5896  0.7335
 2.5487  0.1779 -0.9216
-0.7081 -0.3465  2.4790
 0.4018 -0.6791  0.9201
-0.4824 -0.3940 -0.5191
[torch.FloatTensor of size 5x3]



In [56]:
print(x.add(y))
print(x.add_(y))
print(x)


 0.1945  0.5896  0.7335
 2.5487  0.1779 -0.9216
-0.7081 -0.3465  2.4790
 0.4018 -0.6791  0.9201
-0.4824 -0.3940 -0.5191
[torch.FloatTensor of size 5x3]


 0.1945  0.5896  0.7335
 2.5487  0.1779 -0.9216
-0.7081 -0.3465  2.4790
 0.4018 -0.6791  0.9201
-0.4824 -0.3940 -0.5191
[torch.FloatTensor of size 5x3]


 0.1945  0.5896  0.7335
 2.5487  0.1779 -0.9216
-0.7081 -0.3465  2.4790
 0.4018 -0.6791  0.9201
-0.4824 -0.3940 -0.5191
[torch.FloatTensor of size 5x3]



Матричное умножение:

In [58]:
a = torch.randn(5, 3) 
b = torch.randn(3, 4)

In [63]:
a @ b


-2.5227  1.9708 -1.2437  2.1377
-1.9098  1.5526 -0.7149  1.3484
 1.6840 -1.0705  0.5188 -0.9472
 6.4853 -3.3751  2.2332 -3.7010
-0.5133  0.8365 -0.2499  0.5754
[torch.FloatTensor of size 5x4]

In [66]:
print(torch.mm(a,b))
print(a.mm(b))


-2.5227  1.9708 -1.2437  2.1377
-1.9098  1.5526 -0.7149  1.3484
 1.6840 -1.0705  0.5188 -0.9472
 6.4853 -3.3751  2.2332 -3.7010
-0.5133  0.8365 -0.2499  0.5754
[torch.FloatTensor of size 5x4]


-2.5227  1.9708 -1.2437  2.1377
-1.9098  1.5526 -0.7149  1.3484
 1.6840 -1.0705  0.5188 -0.9472
 6.4853 -3.3751  2.2332 -3.7010
-0.5133  0.8365 -0.2499  0.5754
[torch.FloatTensor of size 5x4]



Изменение размера:

In [67]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Перевод в numpy:

In [68]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [69]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [79]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[ 1.  1.  1.  1.  1.]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]



In [80]:
a += 1
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



Перевод на GPU:

In [81]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

## Графы вычислений, автоматическое дифференцирование

In [2]:
from torch.autograd import Variable

In [60]:
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [61]:
x += 2

RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.

In [62]:
y = x + 2

In [63]:
y.grad_fn

In [64]:
z = y * y * 3
print(z.grad_fn)

In [65]:
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [70]:
out.backward()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [71]:
x.grad

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]

In [49]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)
print(x)

Variable containing:
-0.4664
-0.2301
 0.6428
[torch.FloatTensor of size 3]



In [50]:
y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
 -955.2179
 -471.3261
 1316.3746
[torch.FloatTensor of size 3]



In [51]:
#gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
gradients = torch.FloatTensor([0, 1, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
    0.0000
 2048.0000
    0.2048
[torch.FloatTensor of size 3]



In [52]:
#gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
gradients = torch.FloatTensor([0, 1, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
    0.0000
 4096.0000
    0.4096
[torch.FloatTensor of size 3]



In [53]:
#gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
gradients = torch.FloatTensor([0, 1, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
    0.0000
 6144.0000
    0.6144
[torch.FloatTensor of size 3]



In [54]:
#gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
gradients = torch.FloatTensor([0, 1, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
    0.0000
 8192.0000
    0.8192
[torch.FloatTensor of size 3]

